### ISSUE TITLE
Issue with platform not being set

### ISSUE THREAD

**Issue by aliraeisdanaei** [stepwise-alan/spl-tools#10]
Hey,

I believe I have set up everything correctly, except when I run the command in ``example_toy.sh``
I get the following output. 
```
Warning: No platform header specified
True    parsing succeeded
```
What is the plaform header that I need to specify? Is it part of the ``TypeChef-BusyboxAnalysis?``

If so, Here is how the directory structure looks for ``TypeChef-BusyboxAnalysis?``
```
busybox-1.18.5
├── include
│   ├── acl
│   │   └── libacl.h
...
```

Here is the full output. 
```
 ./example_toy.sh
Running module: EquivalenceChecker

With old file: ./examples/toy/old.c
With new file: ./examples/toy/new.c
Under function: lib

Z3 path: z3
Seahorn path: /home/aliraeis/Projekte/spl-tools/seahorn_docker_run.sh
TypeChef-BusyboxAnalysis path: /home/aliraeis/Projekte/TypeChef-BusyboxAnalysis

Timing out after: 2m

************************************
timeout 2m sbt "runMain EquivalenceChecker ./examples/toy/old.c ./examples/toy/new.c lib z3 /home/aliraeis/Projekte/spl-tools/seahorn_docker_run.sh /home/aliraeis/Projekte/TypeChef-BusyboxAnalysis"
[info] welcome to sbt 1.8.0 (Oracle Corporation Java 1.8.0_362)
[info] loading settings for project spl-tools-build-build from metals.sbt ...
[info] loading project definition from /home/aliraeis/Projekte/spl-tools/project/project
[info] loading settings for project spl-tools-build from metals.sbt ...
[info] loading project definition from /home/aliraeis/Projekte/spl-tools/project
[success] Generated .bloop/spl-tools-build.json
[success] Total time: 1 s, completed 4-Apr-2023 3:43:00 PM
[info] loading settings for project root from build.sbt ...
[info] set current project to spl-tools (in build file:/home/aliraeis/Projekte/spl-tools/)
[info] running EquivalenceChecker ./examples/toy/old.c ./examples/toy/new.c lib z3 /home/aliraeis/Projekte/spl-tools/seahorn_docker_run.sh /home/aliraeis/Projekte/TypeChef-BusyboxAnalysis
Warning: No platform header specified
True    parsing succeeded

Warning: No platform header specified
True    parsing succeeded

Warning: No platform header specified
[error] java.lang.RuntimeException: Nonzero exit value: 109
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:164)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:122)
[error]         at Verifier.getGeneralizedCounterExamples(Verifier.scala:191)
[error]         at Verifier.apply(Verifier.scala:253)
[error]         at EquivalenceChecker$.main(EquivalenceChecker.scala:46)
[error]         at EquivalenceChecker.main(EquivalenceChecker.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / runMain for the full output
[error] (Compile / runMain) Nonzero exit value: 109
[error] Total time: 6 s, completed 4-Apr-2023 3:43:09 PM
java.io.IOError: java.io.IOException: Error executing 'stty -icrnl -echo -icanon -iexten min 0 time 1': 
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
        at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:141)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:371)
        at sbt.xMain$.withStreams$1(Main.scala:87)
        at sbt.xMain$.run(Main.scala:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: Error executing 'stty -icrnl -echo -icanon -iexten min 0 time 1': 
        at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
        at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:101)
        at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
        ... 21 more
[error] [launcher] error during sbt launcher: java.io.IOError: java.io.IOException: Error executing 'stty -icrnl -echo -icanon -iexten min 0 time 1':
```

**Comment by aliraeisdanaei** [comment]
This issue went away after this [merge](https://github.com/stepwise-alan/spl-tools/pull/11)
