### ISSUE TITLE
Invalid Use of Z3

### ISSUE THREAD

**Issue by aliraeisdanaei** [stepwise-alan/spl-tools#12]
Hey, 

I have a new issue, and I think this is due to Z3. 
Here is the main message
``Error: invalid command line option: -m64`` in
``z3 -m64 smt --solve -O0 1.c -o 1.a.smt2 --oll=1.ll``

Here is the full output: 

```./example_toy.sh
Running module: EquivalenceChecker

With old file: ./examples/toy/old.c
With new file: ./examples/toy/new.c
Under function: f

Z3 path: z3
Seahorn path: /home/aliraeis/Projekte/spl-tools/seahorn_docker_run.sh
TypeChef-BusyboxAnalysis path: /home/aliraeis/Projekte/TypeChef-BusyboxAnalysis

Timing out after: 40s

************************************
timeout 40s sbt "runMain EquivalenceChecker ./examples/toy/old.c ./examples/toy/new.c f z3 /home/aliraeis/Projekte/spl-tools/seahorn_docker_run.sh /home/aliraeis/Projekte/TypeChef-BusyboxAnalysis"
[info] welcome to sbt 1.8.0 (Oracle Corporation Java 1.8.0_362)
[info] loading project definition from /home/aliraeis/Projekte/spl-tools/project
[info] loading settings for project root from build.sbt ...
[info] set current project to spl-tools (in build file:/home/aliraeis/Projekte/spl-tools/)
[info] running EquivalenceChecker ./examples/toy/old.c ./examples/toy/new.c f z3 /home/aliraeis/Projekte/spl-tools/seahorn_docker_run.sh /home/aliraeis/Projekte/TypeChef-BusyboxAnalysis
Warning: No platform header specified
#line 1 "./examples/toy/old.c" 1
int f(int x, int y, int z) {
    int r = 0;
#if (definedEx(A) && definedEx(B))
    x = y + 1;
#endif
    while (z > 0) {
#if (definedEx(A) || !definedEx(C))
        r += x;
#endif
#if (!definedEx(A) && definedEx(C))
        r += y;
#endif
        --z;
    }
    return r;
}True   parsing succeeded

Warning: No platform header specified
#line 1 "./examples/toy/new.c" 1
int f(int x, int y, int z) {
    int r = 0;
#if (definedEx(A) && !definedEx(B))
    x = y + 1;
#endif
    while (z > 0) {
#if (definedEx(A) || definedEx(C))
        r += y;
#endif
#if (!definedEx(A) && !definedEx(C))
        r += x;
#endif
        --z;
    }
    return r;
}True   parsing succeeded

Warning: No platform header specified
#line 1 "0.c" 1
int main()
{
  int x;
  int y;
  int z;
  _Bool A;
  _Bool B;
  _Bool C;
  f(x, y, z, A, B, C);
}

int f(int x, int y, int z, _Bool A, _Bool B, _Bool C)
{
  int r_old;
  int r_new;
  int x_old = x;
  int x_new = x;
  int CLEVER_ret_0_old = 0;
  int CLEVER_ret_0_new = 0;
  int r;
  r_old = (r_new = (r = 0));
  if (A && B)
  {
    x_old = y + 1;
  }
  if (A && (!B))
  {
    x_new = y + 1;
  }
  while ((z > 0) || (z > 0))
  {
    if (z > 0)
    {
      if (A || (!C))
      {
        r_old += x_old;
      }
      if (A || C)
      {
        r_new += y;
      }
      if ((!A) && C)
      {
        r_old += y;
      }
      if ((!A) && (!C))
      {
        r_new += x_new;
      }
      --z;
    }
  }

  CLEVER_ret_0_old = r_old;
  CLEVER_ret_0_new = r_new;
  assert(CLEVER_ret_0_old == CLEVER_ret_0_new);
}
z3 -m64 smt --solve -O0 1.c -o 1.a.smt2 --oll=1.ll
Error: invalid command line option: -m64
For usage information: z3 -h
[error] java.lang.RuntimeException: Nonzero exit value: 109
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:164)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:121)
[error]         at Verifier.getGeneralizedCounterExamples(Verifier.scala:197)
[error]         at Verifier.apply(Verifier.scala:264)
[error]         at EquivalenceChecker$.main(EquivalenceChecker.scala:47)
[error]         at EquivalenceChecker.main(EquivalenceChecker.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / runMain for the full output
[error] (Compile / runMain) Nonzero exit value: 109
[error] Total time: 3 s, completed 7-Apr-2023 1:29:07 PM
java.io.IOError: java.io.IOException: Error executing 'stty -icrnl -echo -icanon -iexten min 0 time 1': 
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
        at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:141)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:371)
        at sbt.xMain$.withStreams$1(Main.scala:87)
        at sbt.xMain$.run(Main.scala:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: Error executing 'stty -icrnl -echo -icanon -iexten min 0 time 1': 
        at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
        at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:101)
        at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
        ... 21 more
[error] [launcher] error during sbt launcher: java.io.IOError: java.io.IOException: Error executing 'stty -icrnl -echo -icanon -iexten min 0 time 1':```

**Comment by aliraeisdanaei** [comment]
After taking out each flag that it is screaming at, it is clear the issue is with how z3 is used. The z3 between the branches were installed differently, and so they will have different uses.

The Z3 from this branch was installed through ``pacman`` package manager.

**Comment by aliraeisdanaei** [comment]
```
z3 --version
Z3 version 4.12.0 - 64 bit - build hashcode feda706d0dda2539176246dd221328122c66f77d
```

**Comment by aliraeisdanaei** [comment]
Z3 and seahorn needed to be switch in the order of arguments after merge. Closed [here](https://github.com/aliraeisdanaei/spl-tools/commit/b5c981500da5c095fa82db2ff961fa09f0357379)
