### ISSUE TITLE
Library Dependency is not able to be downloaded by SBT

### ISSUE THREAD

**Issue by aliraeisdanaei** [stepwise-alan/spl-tools#2]
The library dependency for TypeChef is not able to be downloaded. 

I am not sure, if the error is on my part, or the dependency might be out of date for the retreiver. 

**I am keeping this issue here to keep track of; I can attend to it myself.** Take your time ;-)

Here is the what I am trying to do
```
sbt "runMain LiftedEquivalenceCheckerV1 examples/old.c examples/new.c lib"
[info] welcome to sbt 1.6.2 (N/A Java 19.0.2)
[info] loading project definition from /home/aliraeis/Projekte/spl-tools/project
[info] loading settings for project root from build.sbt ...
[info] set current project to spl-tools (in build file:/home/aliraeis/Projekte/spl-tools/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading de.fosd.typechef:frontend_2.13:0.4.2
[error]   Not found
[error]   Not found
[error]   not found: /home/aliraeis/.ivy2/localde.fosd.typechef/frontend_2.13/0.4.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/de/fosd/typechef/frontend_2.13/0.4.2/frontend_2.13-0.4.2.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3690)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error]         at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading de.fosd.typechef:frontend_2.13:0.4.2
[error]   Not found
[error]   Not found
[error]   not found: /home/aliraeis/.ivy2/localde.fosd.typechef/frontend_2.13/0.4.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/de/fosd/typechef/frontend_2.13/0.4.2/frontend_2.13-0.4.2.pom
[error] Total time: 2 s, completed Mar 8, 2023, 4:25:27 p.m.
```

**Comment by aliraeisdanaei** [comment]
This was an issue with the library dependency downloading, and is fixed with better documentation.
